// Copyright 2022 Stefan Kerkmann
// SPDX-License-Identifier: GPL-2.0-or-later

#pragma once

#include "config_common.h"


//#define VENDOR_ID    0xFEED
//#define PRODUCT_ID   0x0004
//#define DEVICE_VER   0x0004
//#define MANUFACTURER EdoBall
//#define PRODUCT Test

#define DEBUG_MATRIX_SCAN_RATE

// #define QMK_WAITING_TEST_BUSY_PIN GP6
// #define QMK_WAITING_TEST_YIELD_PIN GP7

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP25
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U

#define BACKLIGHT_PWM_DRIVER PWMD4
#define BACKLIGHT_PWM_CHANNEL RP2040_PWM_CHANNEL_B

#define AUDIO_PIN GP16
#define AUDIO_PWM_DRIVER PWMD0
#define AUDIO_PWM_CHANNEL RP2040_PWM_CHANNEL_A


#pragma once

#define MATRIX_COL_PINS { GP17, GP16 }
//                          22    21 (Right-Bottom)
#define MATRIX_ROW_PINS { GP14, GP15 }
//                          19    20 (Left-Bottom)

#define MATRIX_ROWS 2
#define MATRIX_COLS 2

#define DIODE_DIRECTION COL2ROW

#define DEBOUNCE 5

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP25
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 500U

#define SERIAL_USART_FULL_DUPLEX
#define SERIAL_USART_TX_PIN GP0
#define SERIAL_USART_RX_PIN GP1

#define SERIAL_DEBUG

#define WS2812_PIO_USE_PIO1

// #define RGB_DI_PIN GP6
#ifdef RGB_DI_PIN
  #define RGBLED_NUM 12
  #define RGBLIGHT_SPLIT
  #define RGBLED_SPLIT { 6, 6 }
  #define RGBLIGHT_LED_MAP { 0, 1, 2, 3, 4, 5, \
                             11, 10, 9, 8, 7, 6 }
  #define RGBLIGHT_HUE_STEP 8
  #define RGBLIGHT_SAT_STEP 8
  #define RGBLIGHT_VAL_STEP 8
  #define RGBLIGHT_LIMIT_VAL 255
  #define RGBLIGHT_SLEEP
  #define RGBLIGHT_EFFECT_RAINBOW_SWIRL
#endif

#define TAPPING_TERM 500
#define PERMISSIVE_HOLD

// ADNS5050
#define ADNS5050_SCLK_PIN GP6
// 9
// default: POINTING_DEVICE_SCLK_PIN
#define ADNS5050_SDIO_PIN GP7
// 10
// default: POINTING_DEVICE_SDIO_PIN
#define ADNS5050_CS_PIN GP8
// 11
// default: POINTING_DEVICE_CS_PIN

#if SPLIT_KEYBOARD == yes
#define MASTER_RIGHT
#define SPLIT_USB_DETECT
#endif
